# Hyprland Blue Light Filter Configuration (hyprsunset)
# Official Docs: https://wiki.hypr.land/Hypr-Ecosystem/hyprsunset/

# Specify night light/temperature parameters here.
# Example:
temperature = 4000
