# ── Keybinds: Applications & Utilities ────────────────────────
bind = $mainMod, RETURN,       exec, uwsm app -- $terminal
bind = $mainMod, J,            exec, ~/bin/workspace.sh
bind = $mainMod, F,            exec, uwsm app -- $fileManager
bind = $mainMod SHIFT, Y,      exec, kitty -e yazi
bind = $mainMod, B,            exec, uwsm app -- $browser
bind = $mainMod, SPACE,        exec, walker
bind = $mainMod, H,            exec, walker --provider clipboard
bind = $mainMod, O,            exec, obsidian
bind = $mainMod, SLASH,        exec, walker --provider files
bind = $mainMod, PERIOD,       exec, walker --provider symbols
bind = $mainMod, TAB,          exec, walker --provider windows
bind = $mainMod SHIFT, SPACE,  exec, pgrep -x waybar && pkill -USR1 waybar || uwsm app -- waybar
bind = $mainMod SHIFT, Escape, exec, uwsm app -- kitty --class floating_btop -e btop
bind = $mainMod SHIFT, W,      exec, ~/.config/hypr/scripts/wallpaper.sh
bind = $mainMod CTRL,  W,      exec, ~/.config/hypr/scripts/wallpaper.sh --next
bind = $mainMod ALT,   W,      exec, ~/.config/hypr/scripts/wallpaper.sh --toggle-daemon

