# Resize Window Binds
# Keybindings for resizing the active window using keyboard shortcuts

binde = $mainMod ALT, left, resizeactive, -30 0
binde = $mainMod ALT, right, resizeactive, 30 0
binde = $mainMod ALT, up, resizeactive, 0 -30
binde = $mainMod ALT, down, resizeactive, 0 30
