# ── Keybinds: Web Applications ────────────────────────────────
bind = SUPER SHIFT, B,  exec, uwsm app -- google-chrome-stable
bind = SUPER, R,        exec, uwsm app -- $browser --new-window --app="https://grok.com"
bind = SUPER, C,        exec, uwsm app -- $browser --new-window --app="https://chat.openai.com/"
bind = SUPER, D,        exec, uwsm app -- $browser --new-window --app="https://chat.deepseek.com"
bind = SUPER, Y,        exec, uwsm app -- $browser --new-window --app="https://www.youtube.com/"
bind = SUPER, W,        exec, uwsm app -- $browser --new-window --app="https://web.whatsapp.com"
bind = SUPER, E,        exec, uwsm app -- $browser --new-window --app="https://mail.google.com"
bind = SUPER, P,        exec, uwsm app -- $browser --new-window --app="https://student.brototype.com"
bind = SUPER, K,        exec, uwsm app -- $browser --new-window --app="https://claude.ai/"
bind = SUPER, G,        exec, uwsm app -- $browser --new-window --app="https://gemini.google.com/"
bind = SUPER, A,        exec, uwsm app -- $browser --new-window --app="https://poe.com/"
bind = SUPER, U,        exec, uwsm app -- $browser --new-window --app="https://www.perplexity.ai/"
bind = SUPER SHIFT, G,  exec, uwsm app -- $browser --new-window --app="https://github.com/rashidnarikkodan"
bind = SUPER SHIFT, H,  exec, uwsm app -- $browser --new-window --app="https://hoppscotch.io"
bind = SUPER SHIFT, D,  exec, uwsm app -- $browser --new-window --app="https://discord.com/channels/@me"
bind = SUPER SHIFT, X,  exec, uwsm app -- $browser --new-window --app="https://x.com/home"
bind = SUPER SHIFT, L,  exec, uwsm app -- $browser --new-window --app="https://linkedin.com/in/rashidnarikkodan"
bind = SUPER SHIFT, F,  exec, uwsm app -- $browser --new-window --app="https://www.figma.com/design/DjUV8IojESAPyGEeGZp4Gl/WashQueue?node-id=0-1&p=f&t=UEpeBQ543vhAXJYH-0"
bind = SUPER SHIFT, E,  exec, uwsm app -- $browser --new-window --app="https://app.eraser.io/workspace/pj9mJ1YwHbjL9x6yheFW"
bind = SUPER SHIFT, P,  exec, uwsm app -- $browser --new-window --app="https://altimetry-geologist-93298022-6358717.postman.co/workspace/My-Workspace~58f52ad7-0015-4961-90f7-9cf7d9be564f/collection/47086432-040ad9d0-f72a-460d-a0ed-8e728a51375a?sideView=variables&action_performed=google_login&authFlowId=2809349a-6924-4a42-96fe-149b6a3bfdd0"
bind = SUPER SHIFT, O,  exec, uwsm app -- $browser --new-window --app="https://cloud.mongodb.com"
