# Layout Configuration
# Official Docs: https://wiki.hypr.land/Configuring/Dwindle-Layout/ & https://wiki.hypr.land/Configuring/Master-Layout/

general {
    layout = dwindle
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}
