# Reusable Variables
# Define standard applications and keys here for ease of switching later.

$mainMod = SUPER

$terminal = kitty
$fileManager = thunar
$browser = brave
$launcher = wofi --show drun
$menu = $launcher
$editor = nano
