#!/bin/bash

# Directory containing wallpapers
WALLPAPER_DIR="$HOME/Pictures/wallpapers"
CONFIG_FILE="$HOME/.config/hypr/hyprpaper.conf"
CACHE_FILE="$HOME/.cache/hyprpaper_current"

# Ensure directory exists
if [ ! -d "$WALLPAPER_DIR" ]; then
    mkdir -p "$WALLPAPER_DIR"
fi

# Get list of wallpapers
get_wallpapers() {
    find "$WALLPAPER_DIR" -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) | sort
}

# Function to update hyprpaper.conf with all preloads
update_config() {
    local WALLPAPERS=($(get_wallpapers))
    if [ ${#WALLPAPERS[@]} -eq 0 ]; then
        return
    fi
    
    echo "# Auto-generated by wallpaper script" > "$CONFIG_FILE"
    for wp in "${WALLPAPERS[@]}"; do
        echo "preload = $wp" >> "$CONFIG_FILE"
    done
    
    # Get current wallpaper or fallback to first one
    local CURRENT_WP=$(cat "$CACHE_FILE" 2>/dev/null)
    if [ -z "$CURRENT_WP" ] || [ ! -f "$CURRENT_WP" ]; then
        CURRENT_WP="${WALLPAPERS[0]}"
    fi
    
    echo "wallpaper = eDP-1,$CURRENT_WP" >> "$CONFIG_FILE"
    echo "splash = false" >> "$CONFIG_FILE"
    echo "ipc = on" >> "$CONFIG_FILE"
}

# Function to set a wallpaper via IPC
set_wallpaper() {
    local WP=$1
    if [ -z "$WP" ]; then return; fi
    
    if pgrep -x "hyprpaper" > /dev/null; then
        hyprctl hyprpaper preload "$WP"
        hyprctl hyprpaper wallpaper "eDP-1,$WP"
    else
        update_config
        hyprpaper &
    fi
    echo "$WP" > "$CACHE_FILE"
}

# Function to set next wallpaper in order
set_next() {
    local WALLPAPERS=($(get_wallpapers))
    if [ ${#WALLPAPERS[@]} -eq 0 ]; then
        echo "No wallpapers found"
        exit 1
    fi
    
    local CURRENT_WP=$(cat "$CACHE_FILE" 2>/dev/null)
    local NEXT_WP=""
    
    if [ -z "$CURRENT_WP" ]; then
        NEXT_WP="${WALLPAPERS[0]}"
    else
        for i in "${!WALLPAPERS[@]}"; do
           if [[ "${WALLPAPERS[$i]}" == "${CURRENT_WP}" ]]; then
               NEXT_WP="${WALLPAPERS[$(( (i + 1) % ${#WALLPAPERS[@]} ))]}"
               break
           fi
        done
        if [ -z "$NEXT_WP" ]; then NEXT_WP="${WALLPAPERS[0]}"; fi
    fi
    
    set_wallpaper "$NEXT_WP"
}

# Function to set random wallpaper
set_random() {
    local WALLPAPERS=($(get_wallpapers))
    if [ ${#WALLPAPERS[@]} -eq 0 ]; then exit 1; fi
    local RANDOM_WP=${WALLPAPERS[$RANDOM % ${#WALLPAPERS[@]}]}
    set_wallpaper "$RANDOM_WP"
}

# Function to start hyprpaper if not running
start_hyprpaper() {
    if pgrep -x "hyprpaper" > /dev/null; then
        pkill -x "hyprpaper"
        sleep 0.5
    fi
    hyprpaper &
    
    # Wait for hyprpaper to initialize IPC
    sleep 1.5
    
    # Force apply the current wallpaper just in case
    local CURRENT_WP=$(cat "$CACHE_FILE" 2>/dev/null)
    if [ -n "$CURRENT_WP" ] && [ -f "$CURRENT_WP" ]; then
        hyprctl hyprpaper preload "$CURRENT_WP" > /dev/null 2>&1
        hyprctl hyprpaper wallpaper "eDP-1,$CURRENT_WP" > /dev/null 2>&1
    fi
}

# Handle arguments
case "$1" in
    --init)
        update_config
        start_hyprpaper
        ;;
    --next)
        set_next
        ;;
    --random)
        set_random
        ;;
    *)
        echo "Usage: $0 {--init|--next|--random}"
        exit 1
        ;;
esac
