# Workspace Rules
# Official Docs: https://wiki.hypr.land/Configuring/Workspace-Rules/

# Smart Gaps (No gaps/borders when only one window is tiled)
workspace = w[tv1], gapsout:0, gapsin:0, border:false
workspace = f[1], gapsout:0, gapsin:0, border:false

# Special Workspaces Configuration (scratchpads)
# Wrapped in 'uwsm app --' for proper systemd cgroups allocation
workspace = special:dev_scratch, on-created-empty:uwsm app -- kitty
